# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessing',
            name='image',
            field=models.ImageField(upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='imageprocessing',
            name='output',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
