# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imageprocessing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/Users/Adhikari/PycharmProjects/static/tmp/'), upload_to=b'')),
                ('default', models.BooleanField()),
            ],
        ),
    ]
