# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 05:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='default',
            field=main.fields.UniqueBooleanField(),
        ),
        migrations.AlterField(
            model_name='binary',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/ubuntu/VISULYTIX_COMPILED_TOOL'), upload_to=b''),
        ),
    ]
