# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 11:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20170706_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField(default=0, max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='binary',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/ubuntu/VISULYTIX_COMPILED_TOOL'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='binary',
            name='hash',
            field=models.CharField(blank=True, default=1499427626, max_length=50),
        ),
    ]
