# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170707_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='hash',
            field=models.CharField(blank=True, default=1499680092, max_length=50),
        ),
    ]
